
# Определяем список сервисов — services
# Эти сервисы будут частью нашего приложения
services:

  app: # Имя сервиса
    container_name: vbot-app
    build:
      # Контекст для сборки образа,
      # в данном случае, текущая директория
      context: .
      # Имя Docker-файла из которого будет собран образ
      dockerfile: Dockerfile
      # Команда, которая будет выполнена после старта сервиса
    entrypoint: ["sh", "-c", "alembic upgrade head && python ./main.py"]
    #command: alembic upgrade head && python ./main.py
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
    ports: # Проброс портов
      - "3000:8000"
    # Перечисляем тома (volumes)
    # Они будут подключены к файловой системе сервиса
    # Например, все что находится в . мы увидим в директории /app
    volumes:
      # Текущая директория пробрасывается в директорию /app внутри контейнера
      # Путь внутри контейнера (после двоеточия) обязательно должен быть абсолютным
      - ".:/app"
      - "/tmp:/tmp"
    # Сервис будет запущен, только после старта db
    depends_on:
      - vbot-db

  vbot-db:
    container_name: vbot-db
    # Имя образа. Здесь мы используем базу данных Postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
      # А так задаются переменные окружения
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
    pgdata: