services:
  app:
    container_name: vbot-app
    restart: always
    stop_signal: SIGINT
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: [ "sh", "-c", "alembic upgrade head && python3 ./src/main.py" ]
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    volumes:
      - ".:/app"
      - "/tmp:/tmp"
    depends_on:
      - vbot-db

  vbot-db:
    container_name: vbot-db
    restart: always
    image: postgres:latest
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata

volumes:
  pgdata: